[project]
name = "ml-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "A113E", email = "amg11amg2@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
ml-course = "ml_course:main"
hello_world = "hello_world:hello"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
